name: clang-format

on:
  push:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.ref }}
    - name: install tools
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main'
        sudo apt-get update
        sudo apt-get install -y clang-format-14
    - name: apply formatter
      run: |
        clang-format-14 -i $(find . -name "*.hpp")
    - name: push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "[clang-format] apply"
        git push
